apiVersion: v1
kind: Service
metadata:
  name: Automated-Deployment
  namespace: namespace-workflow-1710044319686
spec:
  type: LoadBalancer
  selector:
    app: Automated-Deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000